server:
  port: 8081

spring:
  application:
    name: service-users

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/usersdb
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework.security: TRACE

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
