apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MYSQL_PASSWORD: "test1234"     #"your_mysql_password"
  JWT_SECRET:     "2kJ3Z4YkVm1q9XY8Rk8MZwTfLQ0zP1YgW0x9UdN+7hI="   #"your_JWT_secret"