server:
  port: 8080

spring:
  application:
    name: service-tasks

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/tasksdb
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}